config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/', to: 'index#get', as: 'index'
  get 'appdetail/:appID', to: 'app_detail#get', as: 'app_detail'
  post 'review/:appID', to: 'review#post', as: 'review'
  get 'reviews/:appID', to: 'review#get', as: 'reviews'
  get 'search', to: 'search#get', as: 'search'
  get 'author/:authorID', to: 'author#get', as: 'author'
end

app/controllers/app_detail_controller.rb
# frozen_string_literal: true

class AppDetailController < ApplicationController
  include AppsMetrics

  # Fetches the keywords of an app with the given app_id
  # @param app_id [String] the app_id of the app
  # @return [Array<String>] the keywords of the app
  # @example
  #   fetch_keywords('1234')
  #  # => ['keyword1', 'keyword2']
  def fetch_keywords(app_id)
    keywords_sql = "
     SELECT word
     FROM ts_stat('SELECT tsv_search FROM core.\"App\"
     WHERE \"appID\" = #{app_id}')"
    keywords = ActiveRecord::Base.connection.execute(keywords_sql)
    # remove duplicates take first 3 and transform to array
    keywords.to_a.uniq.take(3).map { |k| k['word'] }
  end

  # Fetches the similar apps of an app with the given app_id
  # based on its keywords and order them by the similarity score
  # @param app_id [String] the app_id of the app
  # @return [Array<App>] array of App objects extended with the similarity score
  # @example
  #  fetch_similar_apps('1234')
  # # => [#<App:0x00007f9b0b0b0e00 @score=0.65>, #<App:0x00007f9b0b0b0e00 @score=0.20>]
  # @see https://www.postgresql.org/docs/9.5/textsearch-controls.html
  # @see App
  def fetch_similar_apps(app_id)
    app_id = ActiveRecord::Base.sanitize_sql(app_id)
    sanitized_keywords = fetch_keywords(app_id).map { |k| ActiveRecord::Base.sanitize_sql(k) }
    similar_apps_sql = "
     SELECT score, *
     FROM
     	(SELECT *,ts_rank_cd(a.tsv_search, to_tsquery('#{sanitized_keywords.join('|')}')) AS score
     	FROM core.\"App\" a
     	WHERE a.\"appID\" != #{app_id}) app
     WHERE app.score > 0
     ORDER BY score DESC
     LIMIT 15"

    # Caches the result of the query as this is a very expensive operation and the output changes very rarely.
    # Moreover precomputing on the database side would take too long.
    Rails.cache.fetch(similar_apps_sql, expires_in: 1.day) do
      ActiveRecord::Base.connection.execute(similar_apps_sql).to_a
    end
  end

  # GET /AppDetail/:appID
  # @param :appID [String] the app_id of the app
  def get
    @app = App.left_joins(:Author)
              .select('"App".*, "Author".name AS "authorName"')
              .find_by(appID: params[:appID])
    return render status: 404 if @app.nil?

    # Set the @search variable to be displayed in the search bar
    # @see app/views/layouts/application.html.erb
    @search = @app.name

    @reviews_metrics = app_metics(@app.appID)
    @reviews = Review.where(appID: params[:appID]).order('date DESC, "reviewID" DESC').limit(3)
    @similar_apps = fetch_similar_apps(@app.appID)
  end
end

app/helpers/app_detail_helper.rb
# frozen_string_literal: true

require 'iso-639'

module AppDetailHelper # rubocop:disable Metrics/ModuleLength
  # Converts ISO 639-1 Language Code into ISO 3166-1-alpha-2 Country Code
  # @param [String] lang ISO 639-1 Language Code
  # @return [String] ISO 3166-1-alpha-2 Country Code
  # @example
  #  language_code_to_country_code('en') #=> 'US'
  #  language_code_to_country_code('fr') #=> 'FR'
  #  language_code_to_country_code('es') #=> 'ES'
  #  language_code_to_country_code('de') #=> 'DE'
  def lang_to_flag(lang) # rubocop:disable Metrics/MethodLength
    return nil if lang.nil? || lang.empty?

    codex = {
      aa: 'dj',
      af: 'za',
      ak: 'gh',
      sq: 'al',
      am: 'et',
      az: 'az',
      bm: 'ml',
      be: 'by',
      bn: 'bd',
      bi: 'vu',
      bs: 'ba',
      bg: 'bg',
      my: 'mm',
      ca: 'ad',
      zh: 'cn',
      hr: 'hr',
      cs: 'cz',
      da: 'dk',
      dv: 'mv',
      nl: 'nl',
      dz: 'bt',
      en: 'gb',
      et: 'ee',
      fj: 'fj',
      fil: 'ph',
      fi: 'fi',
      fr: 'fr',
      gaa: 'gh',
      ka: 'ge',
      de: 'de',
      el: 'gr',
      gu: 'in',
      ht: 'ht',
      he: 'il',
      hi: 'in',
      ho: 'pg',
      hu: 'hu',
      is: 'is',
      ig: 'ng',
      id: 'id',
      ga: 'ie',
      it: 'it',
      ja: 'jp',
      kr: 'ne',
      kk: 'kz',
      km: 'kh',
      kmb: 'ao',
      rw: 'rw',
      kg: 'cg',
      ko: 'kr',
      kj: 'ao',
      ku: 'iq',
      ky: 'kg',
      lo: 'la',
      la: 'va',
      lv: 'lv',
      ln: 'cg',
      lt: 'lt',
      lu: 'cd',
      lb: 'lu',
      mk: 'mk',
      mg: 'mg',
      ms: 'my',
      mt: 'mt',
      mi: 'nz',
      mh: 'mh',
      mn: 'mn',
      mos: 'bf',
      ne: 'np',
      nd: 'zw',
      nso: 'za',
      no: 'no',
      nb: 'no',
      nn: 'no',
      ny: 'mw',
      pap: 'aw',
      ps: 'af',
      fa: 'ir',
      pl: 'pl',
      pt: 'pt',
      pa: 'in',
      qu: 'wh',
      ro: 'ro',
      rm: 'ch',
      rn: 'bi',
      ru: 'ru',
      sg: 'cf',
      sr: 'rs',
      srr: 'sn',
      sn: 'zw',
      si: 'lk',
      sk: 'sk',
      sl: 'si',
      so: 'so',
      snk: 'sn',
      nr: 'za',
      st: 'ls',
      es: 'es',
      ss: 'sz',
      sv: 'se',
      tl: 'ph',
      tg: 'tj',
      ta: 'lk',
      te: 'in',
      tet: 'tl',
      th: 'th',
      ti: 'er',
      tpi: 'pg',
      ts: 'za',
      tn: 'bw',
      tr: 'tr',
      tk: 'tm',
      uk: 'ua',
      umb: 'ao',
      ur: 'pk',
      uz: 'uz',
      ve: 'za',
      vi: 'vn',
      cy: 'gb',
      wo: 'sn',
      xh: 'za',
      zu: 'za'
    }

    lang = lang.split('-')[0]
    return nil unless codex.key?(lang.to_sym)

    codex[lang.to_sym]
  end

  # Converts raw number of bytes into human readable format
  # @param [Integer] bytes
  # @return [String]
  # @example
  #  bytes_to_human(1024) #=> "1.0 KB"
  #  bytes_to_human(1024 * 1024) #=> "1.0 MB"
  #  bytes_to_human(1024 * 1024 * 1024) #=> "1.0 GB"
  #  bytes_to_human(1024 * 1024 * 1024 * 1024) #=> "1.0 TB"
  def bytes_to_string(bytes)
    if bytes < 1024
      "#{bytes} B"
    elsif bytes < 1024 * 1024
      "#{(bytes / 1024).to_i} KB"
    elsif bytes < 1024 * 1024 * 1024
      "#{(bytes / 1024 / 1024).to_i} MB"
    else
      "#{(bytes / 1024 / 1024 / 1024).to_i} GB"
    end
  end
end

app/views/app_detail/get.html.erb
<main>
  <% if not @app.blank? %>
    <section class="bg-[<%= @app.colorBg %>] text-[<%= contrast_color(@app.colorBg) %>] xl:p-10 p-5">
      <div class="flex items-center">
        <img class="flex-none rounded-lg w-32 object-scale-down mr-5" src="<%= @app.iconURL %>" alt="<%= @app.name %> Icon">
        <div class="truncate">
          <div class="flex items-center">
            <h1 class="font-bold text-xl m-0"><%= @app.name %></h1>
            <% if not lang_to_flag(@app.lang).nil? %>
              <img src="/flags/<%= lang_to_flag(@app.lang) %>.svg" class="inline-block rounded h-6 ml-2" alt="<%= @app.lang %> flag" title="<%= @app.lang %>" />
            <% elsif not @app.lang.nil? %>
              <span class="inline-block h-6 ml-2"><%= @app.lang %></span>
            <% end %>
          </div>
          <p class="my-2 truncate"><%= @app.description %></p>
          <div>
            <a href="<%= @app.pageURL %>" referrerpolicy="origin-when-cross-origin">
              <button class="text-[<%= contrast_color(@app.colorTheme) %>] bg-[<%= @app.colorTheme %>] font-bold rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 border border-[<%= contrast_color(@app.colorTheme) %>]">
                VISIT
              </button>
            </a>
            <span><%= bytes_to_string(@app.byteSize) %></span>
          </div>
        </div>
      </div>
      <div class="flex xl:gap-x-20 gap-x-7 justify-center items-center mt-2">
        <% if @reviews.length > 0 %>
          <div class="flex xl:gap-x-10 gap-x-2 items-center">
            <div class="flex flex-col items-center">
              <span class="xl:text-xl"><%= @reviews_metrics.average %></span>
              <span class="xl:text-m text-s"><%= @reviews_metrics.total.to_s + " rating" + (@reviews_metrics.total > 1 ? "s" : "") %></span>
            </div>
            <div class="flex">
              <%= render "shared/star", rating: @reviews_metrics.average.to_i, color_active: contrast_color(@app.colorBg) %>
            </div>
          </div>
        <% end %>
        <% if @app.authorID %>
          <%= link_to author_path(@app.authorID), class: "font-bold" do %>
            <button class="text-[<%= contrast_color(@app.colorBg) %>] font-bold rounded-lg text-xs px-2.5 py-2 border border-[<%= contrast_color(@app.colorBg) %>]">
              <%= @app.authorName %>
            </button>
          <% end %>
        <% end %>
      </div>
    </section>
    <section class="text-center my-7">
      <p><%= @app.description %></p>
    </section>
    <section class="flex overflow-x-auto gap-x-10 h-[45vh]">
      <img class="cursor-pointer mb-3 rounded-lg object-contain border border-gray-300"
        src="https://pwa-store.eu-central-1.linodeobjects.com/<%= hash(@app.pageURL) %>/mobile.webp" alt="Screenshot desktop" onclick="window.open(this.src, '_blank');">
      <img class="cursor-pointer mb-3 rounded-lg object-contain border border-gray-300"
        src="https://pwa-store.eu-central-1.linodeobjects.com/<%= hash(@app.pageURL) %>/desktop.webp" alt="Screenshot desktop" onclick="window.open(this.src, '_blank');">
    </section>
    <section>
      <h2 class="text-xl font-bold mb-2">Leave a Review</h2>
      <%= form_with(url: "/Review/" + @app.appID.to_s, method: "post") do |form| %>
        <div class="flex flex-col xl:flex-row gap-x-10 gap-y-5">
          <div class="self-center">
            <% 5.downto(1) do |i| %>
              <div class="flex items-center gap-x-2">
                <%= form.radio_button "rating", i,
                class: "w-4 h-4 border-gray-300 focus:ring-2 focus:ring-blue-300 focus:ring-blue-600 focus:bg-blue-600",
                id: "rating_#{i}",
                checked: i == 3  %>
                <%= form.label "rating_#{i}", i, class: "flex" do %>
                  <%= render 'shared/star', rating: i %>
                <% end %>
              </div>
            <% end %>
          </div>
          <div class="flex-1">
            <%= form.text_area "comment", 
            class: "block p-2.5 w-full min-h-[64px] max-h-[256px] text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500",
            placeholder: "Write your review here...",
            rows: 4,
            required: true %> 
          </div>
          <div class="self-center">
            <%= form.submit "Submit",
              class: "text-[#{contrast_color(@app.colorTheme)}] bg-[#{@app.colorTheme}] font-bold rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 border border-[#{contrast_color(@app.colorTheme)}]"
            %>
          </div>
        </div>
      <% end %>
    </section>

    <% if @reviews.length > 0 %>
      <section class="my-5">
        <h2 class="text-xl font-bold mb-2">Ratings and Reviews</h2>
        <div class="flex flex-col gap-y-4">
          <% @reviews.each do |review| %>
            <%= render 'shared/review', review: review %>
          <% end %>
        </div>
        <% if @reviews.length >= 3 %>
          <div class="flex justify-center">
            <%= link_to reviews_path, class: "font-bold" do %>
              <button class="font-bold rounded-lg text-xs px-2.5 py-2 border">
                See all reviews
              </button>
            <% end %>
          </div>
        <% end %>
      </section>
    <% end %>

    <% unless @similar_apps.length == 0 %>
      <section class="mt-5">
        <h2 class="text-xl font-bold mb-2">Similar PWAs</h2>
        <div class="flex gap-x-5 overflow-x-auto snap-x xl:snap-mandatory">
          <% @similar_apps.each do |similarApp| %>
            <%= link_to app_detail_path(similarApp["appID"]), class: "flex-none snap-start truncate w-32" do %>
              <img class="rounded-lg w-24 h-24 object-scale-down mx-[auto]" src="<%= similarApp["iconURL"] %>" alt="<%= similarApp["name"] %> Icon"
                   title="<%= similarApp["score"] %>">
              <div class="truncate text-center mt-2" title="<%= similarApp["name"] %>">
                <b><%= similarApp["name"] %></b>
              </div>
            <% end %>
          <% end %>
        </div>
      </section>
    <% end %>
  <% else %>
    <section class="text-center my-7">
      <h1>App not found</h1>
    </section>
  <% end %>
</main>